### ISSUE TITLE
automatic closure for bad weather conditions

### ISSUE THREAD

**Issue by spider65** [ara-astronomia/crac-client#25]
A warning message should be displayed in the GUI when the weather conditions are beyond the threshold and server CRaC takes care of the park of the telescope, the closing of the curtains and then of the roof

critical thresholds:
wind, humidity and maybe pressure

**Comment by alkcxy** [comment]
check out for these issue https://github.com/PySimpleGUI/PySimpleGUI/issues/2437

**Comment by alkcxy** [comment]
it depends by https://github.com/ara-astronomia/crac-server/issues/20
